---
name: Automated releases
on:
  push:
    branches:
      - v4
      - v5
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2' ]
    steps:
      - run: ls -la /tmp/
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit
          extensions: sockets pcov
      - name: Install dependencies including dev
        run: composer install
      - name: Tests
        run: composer phpunit-native
      - uses: codecov/codecov-action@v3.1.1
        with:
          files: ./tests/coverage/coverage.xml
          flags: unittests
          name: codecov-umbrella
  code_style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: symplify/easy-coding-standard
      - name: Test code style
        run: ecs
  static_analysis_src:
    name: Static analysis of source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan, psalm
      - name: Install dependencies
        run: composer install --no-dev
      - name: Static analysis (phpstan)
        run: phpstan analyse src
      - name: Static analysis (psalm)
        run: psalm src/
  static_analysis_tests:
    name: Static analysis of tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan, psalm
      - name: Install dependencies including dev
        run: composer install
      - name: Static analysis of tests (psalm)
        run: psalm tests/
      - name: Static analysis of tests (phpstan)
        run: phpstan analyse tests
  docs:
    name: Docs
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpDocumentor
      - name: Generate docs
        run: phpdoc run
      - name: Deploy docs to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
  release:
    name: Automated release
    needs:
      - code_style
      - static_analysis_tests
      - static_analysis_src
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p "@semantic-release/github"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
