---
name: Continuous integration
on:
  push:
    branches:
      - v4
      - v5
  pull_request:
    branches:
      - v4
      - v5
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2
      - run: composer update --no-progress
      - run: composer test
      - uses: codecov/codecov-action@v3.1.1
        with:
         files: ./tests/coverage/coverage.xml
         flags: unittests
         name: codecov-umbrella
  code_style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: symplify/easy-coding-standard
      - name: Test code style
        run: ecs
  static_analysis_src:
    name: Static analysis of source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan, psalm
      - name: Install dependencies
        run: composer install --no-dev
      - name: Static analysis (phpstan)
        run: phpstan analyse src
      - name: Static analysis (psalm)
        run: psalm src/
  static_analysis_tests:
    name: Static analysis of tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan, psalm
      - name: Install dependencies including dev
        run: composer install
      - name: Static analysis of tests (psalm)
        run: psalm tests/
      - name: Static analysis of tests (phpstan)
        run: phpstan analyse tests